feat: support show growth within 7 days
medyagh/gopogh pull request #88
Opened 2023-10-02 10:24 UTC by ComradeProgrammer

feat: support show growth within 7 days

Before:

After:

2023-10-03 19:44 UTC, medyagh reviewed
I am curious 

btw how were u able to generate the Before After data, did u create a dummy SQL database?because I belive the current system works with Cloud SQL, I didnt know we could do local sql?

2023-10-03 19:46 UTC, medyagh commented
as for html formatting we dont have one, but feel free to add one if needed to the makefile

2023-10-03 19:48 UTC, medyagh reviewed
also do we need a new materialized view for the. 7 day

2023-10-09 18:19 UTC, spowelljr requested changes
Consistent formatting

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  let tableCapturedByLambda=table
```suggestion
  let tableCapturedByLambda = table
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  let dateSelect=document.createElement("select")
```suggestion
  let dateSelect = document.createElement("select")
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  dateSelect.innerHTML="<option value=7>7</option>  <option value=15 selected='selected'>15</option>"
```suggestion
  dateSelect.innerHTML = "<option value=7>7</option>  <option value=15 selected='selected'>15</option>"
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  dateSelect.addEventListener("change",async function(event){
```suggestion
  dateSelect.addEventListener("change", async function(event){
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +    const parent=tableCapturedByLambda.parentElement
```suggestion
    const parent = tableCapturedByLambda.parentElement
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +    const dateRange=dateSelect.options[dateSelect.selectedIndex].value
```suggestion
    const dateRange = dateSelect.options[dateSelect.selectedIndex].value
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +    console.log("daterange",dateRange)
```suggestion
```
Delete

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +      console.log(data)
```suggestion
```
Delete

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +      let newTable=createRecentNumberOfFailTable(data.summaryTable,dateRange)
```suggestion
      let newTable = createRecentNumberOfFailTable(data.summaryTable, dateRange)
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +      parent.replaceChild(newTable,tableCapturedByLambda)
```suggestion
      parent.replaceChild(newTable, tableCapturedByLambda)
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +      tableCapturedByLambda=newTable
```suggestion
      tableCapturedByLambda = newTable
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  let wrapper=document.createElement("div")
```suggestion
  let wrapper = document.createElement("div")
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  wrapper.style.width="100%"
```suggestion
  wrapper.style.width = "100%"
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  wrapper.style.textAlign="center"
```suggestion
  wrapper.style.textAlign = "center"
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  wrapper.innerHTML="Show Growth within "
```suggestion
  wrapper.innerHTML = "Show Growth within "
```

2023-10-09 18:19 UTC, spowelljr commented on pkg/handler/flake_chart.html
> +  wrapper.insertAdjacentElement("beforeend",dateSelect)
```suggestion
  wrapper.insertAdjacentElement("beforeend", dateSelect)
```

2023-11-06 19:16 UTC, medyagh approved these changes

2023-11-06 19:16 UTC, merged